# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_maizoro.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(387, 526)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pantalla = QLabel(self.centralwidget)
        self.pantalla.setObjectName(u"pantalla")
        self.pantalla.setGeometry(QRect(7, 15, 371, 71))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(40)
        self.pantalla.setFont(font)
        self.pantalla.setFrameShape(QFrame.Shape.Box)
        self.pantalla.setFrameShadow(QFrame.Shadow.Plain)
        self.pantalla.setLineWidth(2)
        self.pantalla.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.btnAC = QPushButton(self.centralwidget)
        self.btnAC.setObjectName(u"btnAC")
        self.btnAC.setGeometry(QRect(20, 110, 81, 81))
        font1 = QFont()
        font1.setFamilies([u"Impact"])
        font1.setPointSize(30)
        font1.setBold(True)
        font1.setItalic(False)
        self.btnAC.setFont(font1)
        self.btnMasMenos = QPushButton(self.centralwidget)
        self.btnMasMenos.setObjectName(u"btnMasMenos")
        self.btnMasMenos.setGeometry(QRect(110, 110, 81, 81))
        self.btnMasMenos.setFont(font1)
        self.btnPorcentaje = QPushButton(self.centralwidget)
        self.btnPorcentaje.setObjectName(u"btnPorcentaje")
        self.btnPorcentaje.setGeometry(QRect(200, 110, 81, 81))
        self.btnPorcentaje.setFont(font1)
        self.btnEntre = QPushButton(self.centralwidget)
        self.btnEntre.setObjectName(u"btnEntre")
        self.btnEntre.setGeometry(QRect(290, 110, 81, 81))
        self.btnEntre.setFont(font1)
        self.btn7 = QPushButton(self.centralwidget)
        self.btn7.setObjectName(u"btn7")
        self.btn7.setGeometry(QRect(20, 190, 81, 81))
        self.btn7.setFont(font1)
        self.btnMultiplicacion = QPushButton(self.centralwidget)
        self.btnMultiplicacion.setObjectName(u"btnMultiplicacion")
        self.btnMultiplicacion.setGeometry(QRect(290, 190, 81, 81))
        self.btnMultiplicacion.setFont(font1)
        self.btn8 = QPushButton(self.centralwidget)
        self.btn8.setObjectName(u"btn8")
        self.btn8.setGeometry(QRect(110, 190, 81, 81))
        self.btn8.setFont(font1)
        self.btn9 = QPushButton(self.centralwidget)
        self.btn9.setObjectName(u"btn9")
        self.btn9.setGeometry(QRect(200, 190, 81, 81))
        self.btn9.setFont(font1)
        self.btn4 = QPushButton(self.centralwidget)
        self.btn4.setObjectName(u"btn4")
        self.btn4.setGeometry(QRect(20, 270, 81, 81))
        self.btn4.setFont(font1)
        self.btnMenos = QPushButton(self.centralwidget)
        self.btnMenos.setObjectName(u"btnMenos")
        self.btnMenos.setGeometry(QRect(290, 270, 81, 81))
        self.btnMenos.setFont(font1)
        self.btn5 = QPushButton(self.centralwidget)
        self.btn5.setObjectName(u"btn5")
        self.btn5.setGeometry(QRect(110, 270, 81, 81))
        self.btn5.setFont(font1)
        self.btn6 = QPushButton(self.centralwidget)
        self.btn6.setObjectName(u"btn6")
        self.btn6.setGeometry(QRect(200, 270, 81, 81))
        self.btn6.setFont(font1)
        self.btn1 = QPushButton(self.centralwidget)
        self.btn1.setObjectName(u"btn1")
        self.btn1.setGeometry(QRect(20, 350, 81, 81))
        self.btn1.setFont(font1)
        self.btnSuma = QPushButton(self.centralwidget)
        self.btnSuma.setObjectName(u"btnSuma")
        self.btnSuma.setGeometry(QRect(290, 350, 81, 81))
        self.btnSuma.setFont(font1)
        self.btn2 = QPushButton(self.centralwidget)
        self.btn2.setObjectName(u"btn2")
        self.btn2.setGeometry(QRect(110, 350, 81, 81))
        self.btn2.setFont(font1)
        self.btn3 = QPushButton(self.centralwidget)
        self.btn3.setObjectName(u"btn3")
        self.btn3.setGeometry(QRect(200, 350, 81, 81))
        self.btn3.setFont(font1)
        self.btnIgual = QPushButton(self.centralwidget)
        self.btnIgual.setObjectName(u"btnIgual")
        self.btnIgual.setGeometry(QRect(290, 430, 81, 81))
        self.btnIgual.setFont(font1)
        self.btn0 = QPushButton(self.centralwidget)
        self.btn0.setObjectName(u"btn0")
        self.btn0.setGeometry(QRect(20, 430, 171, 81))
        self.btn0.setFont(font1)
        self.btnPunto = QPushButton(self.centralwidget)
        self.btnPunto.setObjectName(u"btnPunto")
        self.btnPunto.setGeometry(QRect(200, 430, 81, 81))
        self.btnPunto.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pantalla.setText(QCoreApplication.translate("MainWindow", u"0123456", None))
        self.btnAC.setText(QCoreApplication.translate("MainWindow", u"AC", None))
        self.btnMasMenos.setText(QCoreApplication.translate("MainWindow", u"+/-", None))
        self.btnPorcentaje.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.btnEntre.setText(QCoreApplication.translate("MainWindow", u"\u00f7", None))
        self.btn7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.btnMultiplicacion.setText(QCoreApplication.translate("MainWindow", u"\u00d7", None))
        self.btn8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.btn9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.btn4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.btnMenos.setText(QCoreApplication.translate("MainWindow", u"\u2212", None))
        self.btn5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.btn6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.btn1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.btnSuma.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.btn2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.btn3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.btnIgual.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.btn0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.btnPunto.setText(QCoreApplication.translate("MainWindow", u".", None))
    # retranslateUi

